#!/bin/sh


gcc -m64 -fPIC -ggdb -c -I/usr/lib/jvm/default-java/include/ -I/usr/lib/jvm/default-java/include/linux -I/usr/local/cuda/include/ CudaRuntime2.c -o CudaRuntime2.o
gcc -m64 -fPIC -ggdb -c -I/usr/lib/jvm/default-java/include/ -I/usr/lib/jvm/default-java/include/linux -I/usr/local/cuda/include/ GpuDeviceSetup.c -o GpuDeviceSetup.o
gcc -m64 -fPIC -ggdb -c -I/usr/lib/jvm/default-java/include/ -I/usr/lib/jvm/default-java/include/linux -I/usr/local/cuda/include/ FastMemory.c -o FastMemory.o
gcc -m64 -fPIC -ggdb -c -I/usr/lib/jvm/default-java/include/ -I/usr/lib/jvm/default-java/include/linux -I/usr/local/cuda/include/ Handles.c -o Handles.o
gcc -m64 -fPIC -ggdb -c -I/usr/lib/jvm/default-java/include/ -I/usr/lib/jvm/default-java/include/linux -I/usr/local/cuda/include/ Cuda2DeviceMemory.c -o Cuda2DeviceMemory.o
gcc -m64 -shared -Wl,-soname,cudaruntime2 -o cudaruntime_x64.so.1 CudaRuntime2.o GpuDeviceSetup.o FastMemory.o Handles.o Cuda2DeviceMemory.o -lc -lcuda
cp cudaruntime_x64.so.1 ../src/edu/syr/pcpratts/rootbeer/runtime2/native/
