/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_syr_pcpratts_rootbeer_runtime_GpuDeviceSetup */

#ifndef _Included_edu_syr_pcpratts_rootbeer_runtime_GpuDeviceSetup
#define _Included_edu_syr_pcpratts_rootbeer_runtime_GpuDeviceSetup
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_syr_pcpratts_rootbeer_runtime_GpuDeviceSetup
 * Method:    doGetDevices
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_edu_syr_pcpratts_rootbeer_runtime_GpuDeviceSetup_doGetDevices
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
